<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ramnath-PC" ignored="0" name="RetryMultipleFailedTestCases" tests="9" failures="2" timestamp="2020-07-25T22:15:18 IST" time="0.265" errors="0">
  <testcase name="test1" time="0.032" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.0" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.0" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.015" classname="mytests.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTests.test1(MyTests.java:9)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.0" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.016" classname="mytests.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTests.test2(MyTests.java:14)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="mytests.MyTests"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
